---
version: "3.8"

services:
  tautulli:
    image: tautulli/tautulli:latest
    container_name: tautulli
    hostname: tautulli
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
      - PUID=1000
      - PGID=1000
    ports:
      - 8181:8181
    volumes:
      - /opt/tautulli/config:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - com.centurylinklabs.watchtower.enable=true