---
version: "3.8"

services:
  tautulli:
    image: tautulli/tautulli:latest
    container_name: tautulli
    hostname: tautulli
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 8181:8181
    volumes:
      - /share/CACHEDEV1_DATA/Container/tautulli/config:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - com.centurylinklabs.watchtower.enable=true
