---
version: "3.8"

services:
  readarr:
    image: linuxserver/readarr:nightly
    container_name: readarr
    hostname: readarr
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
      - PUID=1000
      - PGID=1000
    ports:
      - 8787:8787
    volumes:
      - /opt/readarr/config:/config
      - /data/:/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      - com.centurylinklabs.watchtower.enable=true