---
version: "3.8"

services:
  shlink-postgres:
    image: postgres:latest
    container_name: shlink-postgres
    hostname: shlink-postgres
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - POSTGRES_DB=shlinkdb
      - POSTGRES_USER=shlinkuser
      - POSTGRES_PASSWORD=shlinkpass
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "shlink", "-U", "shlinkuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /share/CACHEDEV1_DATA/Container/shlink/database:/var/lib/postgresql/data
    networks:
      - proxy_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

  shlink:
    image: shlinkio/shlink:stable
    container_name: shlink
    hostname: shlink
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
      - INITIAL_API_KEY=59f4baa0-b67b-444d-8a06-f455b37ec180
      - DB_DRIVER=postgres
      - DB_NAME=shlinkdb
      - DB_USER=shlinkuser
      - DB_PASSWORD=shlinkpass
      - DB_HOST=shlink-postgres
      - DB_PORT=5432
      - DEFAULT_DOMAIN=shlink.thenoisykeyboard.com
      - IS_HTTPS_ENABLED=true
      - GEOLITE_LICENSE_KEY=ot1mmLCACB3N8IL6
    ports:
      - 8335:8080
    depends_on:
      shlink-postgres:
        condition: service_started
    networks:
      - proxy_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

  shlink-web:
    image: shlinkio/shlink-web-client:stable
    container_name: shlink-web
    hostname: shlink-web
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80/ || exit 1
    environment:
      - SHLINK_SERVER_NAME=thenoisykeyboard
      - SHLINK_SERVER_URL=https://shlink.thenoisykeyboard.com
      - SHLINK_SERVER_API_KEY=59f4baa0-b67b-444d-8a06-f455b37ec180
    ports:
      - 8336:80
    depends_on:
      - shlink
    networks:
      - proxy_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  proxy_network:
    name: proxy_network
    external: true