---
version: "3.8"

services:
  duplicati:
    image: ghcr.io/linuxserver/duplicati:latest
    container_name: duplicati
    hostname: duplicati
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 8200:8200
    volumes:
      - /share/CACHEDEV1_DATA/Container/duplicati/backups:/backups
      - /share/CACHEDEV1_DATA/Container/duplicati/config:/config
      - /share/CACHEDEV1_DATA/Container:/source
      - /etc/localtime:/etc/localtime:ro
    labels:
      - com.centurylinklabs.watchtower.enable=true
