---
version: "3.8"

services:
  duplicati:
    image: ghcr.io/linuxserver/duplicati:latest
    container_name: duplicati
    hostname: duplicati
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
      - PUID=1000
      - PGID=1000
    ports:
      - 8200:8200
    volumes:
      - /opt/duplicati/backups:/backups
      - /opt/duplicati/config:/config
      - /opt:/source
      - /etc/localtime:/etc/localtime:ro
    labels:
      - com.centurylinklabs.watchtower.enable=true