---
version: "3.8"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    hostname: vaultwarden
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    user: 1000:1000
    env_file:
      - .env
    environment:
      - TZ=${TZ}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - DOMAIN=${DOMAIN}
      - EMERGENCY_ACCESS_ALLOWED=${EMERGENCY_ACCESS_ALLOWED}
      - INVITATIONS_ALLOWED=${INVITATIONS_ALLOWED}
      - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED}
      - WEB_VAULT_ENABLED=${WEB_VAULT_ENABLED}
    ports:
      - 9445:80
      - 3012:3012
    volumes:
      - /opt/vaultwarden/config:/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      - com.centurylinklabs.watchtower.enable=true