---
version: "3.8"

services:
  gitea_postgres:
    image: postgres:latest
    container_name: gitea_postgres
    hostname: gitea_postgres
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    environment:
      - TZ=${TZ}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGUSER=${PGUSER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - /share/CACHEDEV1_DATA/Container/gitea/database:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    hostname: gitea
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    environment:
      - TZ=${TZ}
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
      - GITEA__database__DB_TYPE=${GITEA__database__DB_TYPE}
      - GITEA__database__HOST=${GITEA__database__HOST}
      - GITEA__database__NAME=${GITEA__database__NAME}
      - GITEA__database__USER=${GITEA__database__USER}
      - GITEA__database__PASSWD=${GITEA__database__PASSWD}
    ports:
      - 3000:3000
      - 222:22
    volumes:
      - /share/CACHEDEV1_DATA/Container/gitea/config:/data
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      gitea_postgres:
        condition: service_healthy
    networks:
      - proxy_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  proxy_network:
    name: proxy_network
    external: true
