---
version: "3.8"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    hostname: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
      - CF_API_EMAIL=troy_rippin@icloud.com
      - CF_DNS_API_TOKEN=v6u5PyhZZvbiMxTmEV_zcvchC8XGlI6EkCCejhyT
      # - CF_API_KEY=YOU_API_KEY
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - /share/CACHEDEV1_DATA/Container/traefik/config/traefik.yml:/traefik.yml:ro
      - /share/CACHEDEV1_DATA/Container/traefik/config/config.yml:/config.yml:ro
      - /share/CACHEDEV1_DATA/Container/traefik/config/acme.json:/acme.json
      - /share/CACHEDEV1_DATA/Container/traefik/logs:/var/log/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      # - traefik.http.routers.traefik.rule=Host(`dashboard.thenoisykeyboard.com`)
      - traefik.http.middlewares.traefik-auth.basicauth.users=troy:$$apr1$$GwhAzNPW$$/FHgrqi6AWGoU5sY.il3Y1
      - traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.traefik.middlewares=traefik-https-redirect
      - traefik.http.routers.traefik-secure.entrypoints=https
      # - traefik.http.routers.traefik-secure.rule=Host(`dashboard.thenoisykeyboard.com`)
      - traefik.http.routers.traefik-secure.middlewares=traefik-auth
      - traefik.http.routers.traefik-secure.tls=true
      - traefik.http.routers.traefik-secure.tls.certresolver=cloudflare
      - traefik.http.routers.traefik-secure.tls.domains[0].main=thenoisykeyboard.com
      - traefik.http.routers.traefik-secure.tls.domains[0].sans=*.thenoisykeyboard.com
      - traefik.http.routers.traefik-secure.service=api@internal

networks:
  proxy:
    name: proxy
    external: true