---
version: "3.8"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    user: 0:0
    environment:
      - TZ=Europe/Stockholm
    ports:
      - 3000:3000
    volumes:
      - /opt/grafana/data:/var/lib/grafana
    labels:
      - com.centurylinklabs.watchtower.enable=true