---
version: "3.8"

services:
  nextcloud_postgres:
    image: postgres:latest
    container_name: nextcloud_postgres
    hostname: nextcloud_postgres
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    environment:
      - TZ=${TZ}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGUSER=${PGUSER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - /opt/nextcloud/database:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - nextcloud_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    hostname: nextcloud
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    environment:
      - TZ=${TZ}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 8080:80
    volumes:
      - /opt/nextcloud/config:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      nextcloud_postgres:
        condition: service_healthy
    networks:
      - nextcloud_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  nextcloud_network:
    name: nextcloud_network
    external: true