---
version: "3.8"

services:
  nextcloud_mariadb:
    image: mariadb:latest
    container_name: nextcloud_mariadb
    hostname: nextcloud_mariadb
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    environment:
      - TZ=${TZ}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: "healthcheck.sh --connect"
      start_period: 1m
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /share/CACHEDEV1_DATA/Container/nextcloud/database:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    networks:
      - nextcloud_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    hostname: nextcloud
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    environment:
      - TZ=${TZ}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 8080:80
    volumes:
      - /share/CACHEDEV1_DATA/Container/nextcloud/config:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      nextcloud_mariadb:
        condition: service_healthy
    networks:
      - nextcloud_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  nextcloud_network:
    name: nextcloud_network
    external: true
