---
version: "3.8"

services:
 phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    hostname: phpmyadmin
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
      - PMA_HOST=
      - PMA_PORT=3306
    ports:
      - 80:80
    volumes:
      - /opt/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - /opt/phpmyadmin/sessions:/sessions
      - /opt/phpmyadmin/themes/boodark-teal:/var/www/html/themes/boodark-teal/
      - /etc/localtime:/etc/localtime:ro
    labels:
      - com.centurylinklabs.watchtower.enable=true