---
version: "3.8"

services:
  wordpress_mysql:
    image: mysql:latest
    container_name: wordpress_mysql
    hostname: wordpress_mysql
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    environment:
      - TZ=${TZ}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - 3306:3306
    volumes:
      - /opt/wordpress/database:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    networks:
      - wordpress_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    hostname: wordpress
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    environment:
      - TZ=${TZ}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    ports:
      - 8000:80
    volumes:
      - /opt/wordpress/config:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      wordpress_mysql:
        condition: service_healthy
    networks:
      - wordpress_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  wordpress_network:
    name: wordpress_network
    external: true