---
version: "3.8"

services:
  pingvin-share:
    image: stonith404/pingvin-share:latest
    container_name: pingvin-share
    hostname: pingvin-share
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
    ports:
      - 3000:3000
    volumes:
      - /opt/pingvin-share/data:/opt/app/backend/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      - com.centurylinklabs.watchtower.enable=true