---
version: "3.8"

services:
  restic_backup:
    image: mazzolino/restic
    container_name: restic_backup
    hostname: restic_backup
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
      - RUN_ON_STARTUP: "true"
      - BACKUP_CRON: "0 */12 * * *" #this is twice daily, i.e., every 12 hours
      - RESTIC_REPOSITORY: /restic
      - RESTIC_PASSWORD:
      - RESTIC_BACKUP_SOURCES: /mnt/volumes
      - RESTIC_COMPRESSION: auto 
      - RESTIC_BACKUP_ARGS: >-
        --tag restic-proxmox #add tags, whatever you need to mark backups
        --verbose
      - RESTIC_FORGET_ARGS: >- #change as required
        --keep-last 10
        --keep-daily 7
        --keep-weekly 5
        --keep-monthly 12
    volumes:
      - /opt/restic/backups:/restic
      - /opt/restic/tmp-for-restore:/tmp-for-restore
      - /opt:/mnt/volumes:ro
    labels:
      - com.centurylinklabs.watchtower.enable=true

  restic_prune:
    image: mazzolino/restic
    container_name: restic_prune
    hostname: restic_prune
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
      - RUN_ON_STARTUP: "true"
      - PRUNE_CRON: "0 0 4 * * *"
      - RESTIC_REPOSITORY: /restic
      - RESTIC_PASSWORD:
    labels:
      - com.centurylinklabs.watchtower.enable=true

  restic_check:
    image: mazzolino/restic
    container_name: restic_check
    hostname: restic_check
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
      - RUN_ON_STARTUP: "false"
      - CHECK_CRON: "0 15 5 * * *"
      - RESTIC_CHECK_ARGS: >-
        --read-data-subset=10%
      - RESTIC_REPOSITORY: /restic
      - RESTIC_PASSWORD:
    labels:
      - com.centurylinklabs.watchtower.enable=true