---
version: "3.8"

services:
  ghost_mariadb:
    image: mariadb:latest
    container_name: ghost_mariadb
    hostname: ghost_mariadb
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: "healthcheck.sh --connect"
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - 3306:3306
    volumes:
      - /opt/ghost/database:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    networks:
      - ghost_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

  ghost:
    image: ghost:latest
    container_name: ghost
    hostname: ghost
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    environment:
      - TZ=${TZ}
      - database__client=${database__client}
      - database__connection__host=${database__connection__host}
      - database__connection__database=${database__connection__database}
      - database__connection__user=${database__connection__user}
      - database__connection__password=${database__connection__password}
      - url=${url}
    ports:
      - 2368:2368
    volumes:
      - /opt/ghost/config:/var/lib/ghost/content
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      ghost_mariadb:
        condition: service_healthy
    networks:
      - ghost_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  ghost_network:
    name: ghost_network
    external: true