---
version: "3.8"

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    hostname: transmission
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - /share/CACHEDEV1_DATA/Container/transmission/config:/config
      - /share/CACHEDEV1_DATA/data/torrents:/data/torrents/
      - /share/CACHEDEV1_DATA/Container/transmission/config:/watch
      - /etc/localtime:/etc/localtime:ro
    labels:
      - com.centurylinklabs.watchtower.enable=true
