---
version: "3.8"

services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    hostname: zigbee2mqtt
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
    ports:
      - 9110:8080
    volumes:
      - /opt/zigbee2mqtt/config:/app/data
      - /run/udev:/run/udev:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0
    labels:
      - com.centurylinklabs.watchtower.enable=true