---
version: "3.8"

services:
 influxdb:
    image: influxdb:latest
    container_name: influxdb
    hostname: influxdb
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
    ports:
      - 8086:8086
    volumes:
      - /opt/influxdb/config:/etc/influxdb2
      - /opt/influxdb/data:/var/lib/influxdb2
      - /etc/localtime:/etc/localtime:ro
    labels:
      - com.centurylinklabs.watchtower.enable=true