---
version: "3.8"

services:
  wireguard:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wireguard
    hostname: wireguard
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
      - WG_HOST=mydomain.com
      - PASSWORD=
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.1.1.x
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_ALLOWED_IPS=192.168.1.0/24
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    volumes:
      - /opt/wireguard:/etc/wireguard
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - com.centurylinklabs.watchtower.enable=true