---
version: "3.8"

services:
  nginx_proxy_manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_manager
    hostname: nginx_proxy_manager
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
      - DB_SQLITE_FILE=/data/database.sqlite
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - /opt/nginx-proxy-manager/config/data:/data
      - /opt/nginx-proxy-manager/config/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  proxy_network:
    name: proxy_network
    external: true