---
version: "3.8"

services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    hostname: dockge
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
      - DOCKGE_STACKS_DIR=/opt/stacks
    ports:
      - 5001:5001
    volumes:
      - /opt/dockge/config:/app/data
      - /opt/stacks:/opt/stacks
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    labels:
      - com.centurylinklabs.watchtower.enable=true