---
version: "3.8"

services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    hostname: dockge
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    environment:
      - TZ=${TZ}
      - DOCKGE_STACKS_DIR=${DOCKGE_STACKS_DIR}
    ports:
      - 5001:5001
    volumes:
      - /share/CACHEDEV1_DATA/Container/dockge/config:/app/data
      - /share/CACHEDEV1_DATA/Container/stacks:/share/CACHEDEV1_DATA/Container/stacks
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  proxy_network:
    name: proxy_network
    external: true
